version: '3.8'

services:
  messenger:
    build: .
    container_name: 'messenger'
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '2000:3000'
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    container_name: 'messenger_database'
