version: '3.8'

services:
  messenger:
    build: .
    container_name: 'messenger'
    networks:
      - webnet
    environment:
      DB_HOST: database
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '2000:3000'
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: 'messenger_database'
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
networks:
  webnet:
