version: '3.3'

services:
  messenger:
    build: .
    command: yarn start:dev
    container_name: 'messenger'
    networks:
      - webnet
    environment:
      DB_HOST: database
      AWS_S3_BUCKET_NAME: apta-images
      AWS_ACCESS_KEY_ID: AKIA3OSDG5XW6EJDKWUG
      AWS_SECRET_ACCESS_KEY: 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
      ONESIGNAL_TOKEN: ZmZiMTA2MjYtNmJkMC00MzZjLTlmNTQtODkzZTdkOTNiODgw
      ONESIGNAL_APP_ID: 49a6a3ff-11a1-488a-a223-675a91e23653
      ONESIGNAL_API_URL: https://onesignal.com/api/v1/
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '3000:3000'
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: 'messenger_database'
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: teste
networks:
  webnet:
